name: guardian_ai
description: Cross-platform app protecting seniors from scams.
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  encrypt: ^5.0.1
  sqflite: ^2.2.5
  path_provider: ^2.0.11
  local_auth: ^2.1.0
  provider: ^6.0.3
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
